language: node_js
node_js:
  - '6'
env:
  global:
    - URL_DEV: vbikbaev-burberry-fake-shop-for-study-dev
    - URL_PROD: vbikbaev-burberry-fake-shop-for-study

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  - provider: script
    script: now alias $(now build -t=$NOW_TOKEN --public) $URL_DEV -t=$NOW_TOKEN
    on:
      branch: develop

  - provider: script
    script: now alias $(now build -t=$NOW_TOKEN --public) $URL_PROD -t=$NOW_TOKEN
    on:
      branch: master