language: node_js
node_js:
  - '6'
env:
  global:
    - URL_DEV: vbikbaev-burberry-fake-shop-for-study-dev
    - URL_PROD: vbikbaev-burberry-fake-shop-for-study

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run test

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      npm run build && now alias $(now build -t=$NOW_TOKEN --public) $URL_PROD -t=$NOW_TOKEN;
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then
      npm run build && now alias $(now build -t=$NOW_TOKEN --public) $URL_DEV -t=$NOW_TOKEN;